<a href="https://colab.research.google.com/github/Napokue/pytorch-deep-learning-in-a-day/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
print(TENSOR[0])
print(TENSOR[0][0])
print(TENSOR[0][0][0])
print(TENSOR[0][1][1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(5)


### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0257, 0.0692, 0.8868, 0.6466],
        [0.8888, 0.7513, 0.1271, 0.3203],
        [0.1651, 0.7761, 0.6443, 0.8337]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# torch.range() is deprecated, use torch.arange()
one_to_ten = torch.arange(0, 10, 1)
one_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes 

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is the tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 5, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 5, 9], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 30., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - To get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - To get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - To get device from a tensor, can use `tensor.device`

In [30]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2260, 0.3848, 0.4106, 0.2812],
        [0.3046, 0.4255, 0.6860, 0.8086],
        [0.3733, 0.0445, 0.4100, 0.4977]])

In [31]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2260, 0.3848, 0.4106, 0.2812],
        [0.3046, 0.4255, 0.6860, 0.8086],
        [0.3733, 0.0445, 0.4100, 0.4977]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [35]:
# Try out PyTorch intrinsic functions
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performaing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [36]:
# Element wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [37]:
# Matrix multiplication
print(f"{tensor} * {tensor} = {torch.matmul(tensor, tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = 14


In [38]:
# Matrix multiplication by hand
print(f"{tensor} * {tensor} = {(tensor[0] * tensor[0]) + (tensor[1] * tensor[1]) + (tensor[2] * tensor[2])}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = 14


In [39]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 314 µs, sys: 59 µs, total: 373 µs
Wall time: 959 µs


tensor(14)

In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 91 µs, sys: 0 ns, total: 91 µs
Wall time: 623 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [41]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

print(f"Shape of tensor_A: {tensor_A.shape}")
print(f"Shape of tensor_B: {tensor_B.shape}")

# torch.mm is the same as torch.matmul (it's an alias for writing less code)

# Following line cannot be run, as the inner dimensions of the matrices are not equal
# torch.mm(tensor_A, tensor_B) 

Shape of tensor_A: torch.Size([3, 2])
Shape of tensor_B: torch.Size([3, 2])


To fix the tensor shape issues, the shape of one of the tensor can be manipulated using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [42]:
print(f"Original tensor_B: {tensor_B}")
print(f"Original shape of tensor_B: {tensor_B.shape}")

print(f"Transposed tensor_B: {tensor_B.T}")
print(f"Transposed shape of tensor_B: {tensor_B.T.shape}")

Original tensor_B: tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
Original shape of tensor_B: torch.Size([3, 2])
Transposed tensor_B: tensor([[ 7,  8,  9],
        [10, 11, 12]])
Transposed shape of tensor_B: torch.Size([2, 3])


In [43]:
# Now the matrix multiplication works, as the matrix of tensor_B has been transposed
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
torch.mm(tensor_A, tensor_B.T)

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding, the min, max, mean, sum, etc (tensor aggregation)

In [44]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [46]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [47]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [49]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [50]:
# Find the position in tensor that has the maximum value with argmin()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezin and unsqueezin tensors

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueezing - Adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimension permutted (swapped) in a certain way

In [51]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# Changing z changes x (because a view of a tensor shared the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [55]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [61]:
# torch.squeeze() - Removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension form x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [62]:
# torch.unsqueeze() - Adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [66]:
# torch.permute - Rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, weight, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
