<a href="https://colab.research.google.com/github/Napokue/pytorch-deep-learning-in-a-day/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
print(TENSOR[0])
print(TENSOR[0][0])
print(TENSOR[0][0][0])
print(TENSOR[0][1][1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(5)


### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6635, 0.9614, 0.0342, 0.3115],
        [0.4814, 0.0992, 0.9419, 0.1430],
        [0.6975, 0.5281, 0.7401, 0.2276]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# torch.range() is deprecated, use torch.arange()
one_to_ten = torch.arange(0, 10, 1)
one_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes 

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is the tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 5, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 5, 9], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 30., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - To get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - To get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - To get device from a tensor, can use `tensor.device`

In [30]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3012, 0.5542, 0.2444, 0.3475],
        [0.6912, 0.6091, 0.3059, 0.8092],
        [0.2149, 0.1679, 0.9848, 0.8520]])

In [31]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3012, 0.5542, 0.2444, 0.3475],
        [0.6912, 0.6091, 0.3059, 0.8092],
        [0.2149, 0.1679, 0.9848, 0.8520]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [36]:
# Try out PyTorch intrinsic functions
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performaing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [37]:
# Element wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [41]:
# Matrix multiplication
print(f"{tensor} * {tensor} = {torch.matmul(tensor, tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = 14


In [44]:
# Matrix multiplication by hand
print(f"{tensor} * {tensor} = {(tensor[0] * tensor[0]) + (tensor[1] * tensor[1]) + (tensor[2] * tensor[2])}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = 14


In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.91 ms, sys: 0 ns, total: 1.91 ms
Wall time: 1.93 ms


tensor(14)

In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 122 µs, sys: 14 µs, total: 136 µs
Wall time: 144 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [65]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

print(f"Shape of tensor_A: {tensor_A.shape}")
print(f"Shape of tensor_B: {tensor_B.shape}")

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

Shape of tensor_A: torch.Size([3, 2])
Shape of tensor_B: torch.Size([3, 2])


To fix the tensor shape issues, the shape of one of the tensor can be manipulated using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [69]:
print(f"Original tensor_B: {tensor_B}")
print(f"Original shape of tensor_B: {tensor_B.shape}")

print(f"Transposed tensor_B: {tensor_B.T}")
print(f"Transposed shape of tensor_B: {tensor_B.T.shape}")

Original tensor_B: tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
Original shape of tensor_B: torch.Size([3, 2])
Transposed tensor_B: tensor([[ 7,  8,  9],
        [10, 11, 12]])
Transposed shape of tensor_B: torch.Size([2, 3])


In [71]:
# Now the matrix multiplication works, as the matrix of tensor_B has been transposed
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
torch.mm(tensor_A, tensor_B.T)

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])